/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class MainDialog extends javax.swing.JDialog {
    private java.awt.Frame parentFrame;
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MEDetails = new javax.swing.JButton();
        btn_MAttendance = new javax.swing.JButton();
        btn_MExit = new javax.swing.JButton();
        btn_MWHours = new javax.swing.JButton();
        btn_MPPayroll = new javax.swing.JButton();
        lbl_main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");

        btn_MEDetails.setText("Employee Details");
        btn_MEDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MEDetailsActionPerformed(evt);
            }
        });

        btn_MAttendance.setText("Attendance");
        btn_MAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MAttendanceActionPerformed(evt);
            }
        });

        btn_MExit.setText("Exit");
        btn_MExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MExitActionPerformed(evt);
            }
        });

        btn_MWHours.setText("Work Hours");
        btn_MWHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MWHoursActionPerformed(evt);
            }
        });

        btn_MPPayroll.setText("Process Payroll");
        btn_MPPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MPPayrollActionPerformed(evt);
            }
        });

        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("MotorPH Payroll System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_MEDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(btn_MAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MWHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MPPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_MExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_main))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MEDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MWHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MPPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MEDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MEDetailsActionPerformed

        String searchId = JOptionPane.showInputDialog(this, "Enter Employee ID to search:");

    if (searchId != null && !searchId.trim().isEmpty()) {
        boolean found = false;

        try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\HP\\OneDrive\\Desktop\\CP2\\Motorph\\employee.csv"))) {
            String line;
            boolean skipHeader = true;

            while ((line = br.readLine()) != null) {
                if (skipHeader) {
                    skipHeader = false;
                    continue;
                }

                String[] data = line.split(",");
                if (data.length > 0 && data[0].trim().equalsIgnoreCase(searchId.trim())) {
                    Employee emp = new Employee(data);  // assumes you have a constructor like: Employee(String[] data)

                    Employee_DetailsResult dialog = new Employee_DetailsResult(parentFrame, true);
                    dialog.setEmployeeDetails(emp);
                    dialog.setVisible(true);
                    found = true;
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Employee ID not found.", "Not Found", JOptionPane.WARNING_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading employee file: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        } } 
        // TODO add your handling code here: 
    }//GEN-LAST:event_btn_MEDetailsActionPerformed

    private void btn_MAttendanceActionPerformed(java.awt.event.ActionEvent evt) {                                                
//GEN-FIRST:event_btn_MAttendanceActionPerformed
    View_Attendance attendance = new View_Attendance(null, true);
attendance.setVisible(true);
    }//GEN-LAST:event_btn_MAttendanceActionPerformed

    private void btn_MExitActionPerformed(java.awt.event.ActionEvent evt) {                                          
//GEN-FIRST:event_btn_MExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btn_MExitActionPerformed

    private void btn_MWHoursActionPerformed(java.awt.event.ActionEvent evt) {                                            
//GEN-FIRST:event_btn_MWHoursActionPerformed
    View_Attendance workHours = new View_Attendance(null, true);
workHours.setVisible(true);
    }//GEN-LAST:event_btn_MWHoursActionPerformed

    private void btn_MPPayrollActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MPPayrollActionPerformed
    this.setVisible(false); // Hide main dialog while payroll is open
    java.awt.EventQueue.invokeLater(() -> {
        new ProcessPayroll().setVisible(true);
    });
    }//GEN-LAST:event_btn_MPPayrollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            MainDialog dialog = new MainDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MAttendance;
    private javax.swing.JButton btn_MEDetails;
    private javax.swing.JButton btn_MExit;
    private javax.swing.JButton btn_MPPayroll;
    private javax.swing.JButton btn_MWHours;
    private javax.swing.JLabel lbl_main;
    // End of variables declaration//GEN-END:variables

    // ✅ Custom fields (inside class)
    private javax.swing.JTable payrollTable;
    private javax.swing.JScrollPane payrollScrollPane;
    private javax.swing.table.DefaultTableModel payrollTableModel;

} // 
